# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_halite')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_halite')
    _halite = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_halite', [dirname(__file__)])
        except ImportError:
            import _halite
            return _halite
        if fp is not None:
            try:
                _mod = imp.load_module('_halite', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _halite = swig_import_helper()
    del swig_import_helper
else:
    import _halite
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _halite.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self) -> "PyObject *":
        return _halite.SwigPyIterator_value(self)

    def incr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _halite.SwigPyIterator_incr(self, n)

    def decr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _halite.SwigPyIterator_decr(self, n)

    def distance(self, x: 'SwigPyIterator') -> "ptrdiff_t":
        return _halite.SwigPyIterator_distance(self, x)

    def equal(self, x: 'SwigPyIterator') -> "bool":
        return _halite.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _halite.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _halite.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _halite.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _halite.SwigPyIterator_previous(self)

    def advance(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _halite.SwigPyIterator_advance(self, n)

    def __eq__(self, x: 'SwigPyIterator') -> "bool":
        return _halite.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: 'SwigPyIterator') -> "bool":
        return _halite.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _halite.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _halite.SwigPyIterator___isub__(self, n)

    def __add__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _halite.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _halite.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _halite.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class UniConnectionVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UniConnectionVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UniConnectionVector, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _halite.UniConnectionVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _halite.UniConnectionVector___nonzero__(self)

    def __bool__(self) -> "bool":
        return _halite.UniConnectionVector___bool__(self)

    def __len__(self) -> "std::vector< UniConnection >::size_type":
        return _halite.UniConnectionVector___len__(self)

    def __getslice__(self, i: 'std::vector< UniConnection >::difference_type', j: 'std::vector< UniConnection >::difference_type') -> "std::vector< UniConnection,std::allocator< UniConnection > > *":
        return _halite.UniConnectionVector___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _halite.UniConnectionVector___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< UniConnection >::difference_type', j: 'std::vector< UniConnection >::difference_type') -> "void":
        return _halite.UniConnectionVector___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _halite.UniConnectionVector___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< UniConnection >::value_type const &":
        return _halite.UniConnectionVector___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _halite.UniConnectionVector___setitem__(self, *args)

    def pop(self) -> "std::vector< UniConnection >::value_type":
        return _halite.UniConnectionVector_pop(self)

    def append(self, x: 'UniConnection') -> "void":
        return _halite.UniConnectionVector_append(self, x)

    def empty(self) -> "bool":
        return _halite.UniConnectionVector_empty(self)

    def size(self) -> "std::vector< UniConnection >::size_type":
        return _halite.UniConnectionVector_size(self)

    def swap(self, v: 'UniConnectionVector') -> "void":
        return _halite.UniConnectionVector_swap(self, v)

    def begin(self) -> "std::vector< UniConnection >::iterator":
        return _halite.UniConnectionVector_begin(self)

    def end(self) -> "std::vector< UniConnection >::iterator":
        return _halite.UniConnectionVector_end(self)

    def rbegin(self) -> "std::vector< UniConnection >::reverse_iterator":
        return _halite.UniConnectionVector_rbegin(self)

    def rend(self) -> "std::vector< UniConnection >::reverse_iterator":
        return _halite.UniConnectionVector_rend(self)

    def clear(self) -> "void":
        return _halite.UniConnectionVector_clear(self)

    def get_allocator(self) -> "std::vector< UniConnection >::allocator_type":
        return _halite.UniConnectionVector_get_allocator(self)

    def pop_back(self) -> "void":
        return _halite.UniConnectionVector_pop_back(self)

    def erase(self, *args) -> "std::vector< UniConnection >::iterator":
        return _halite.UniConnectionVector_erase(self, *args)

    def __init__(self, *args):
        this = _halite.new_UniConnectionVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x: 'UniConnection') -> "void":
        return _halite.UniConnectionVector_push_back(self, x)

    def front(self) -> "std::vector< UniConnection >::value_type const &":
        return _halite.UniConnectionVector_front(self)

    def back(self) -> "std::vector< UniConnection >::value_type const &":
        return _halite.UniConnectionVector_back(self)

    def assign(self, n: 'std::vector< UniConnection >::size_type', x: 'UniConnection') -> "void":
        return _halite.UniConnectionVector_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _halite.UniConnectionVector_resize(self, *args)

    def insert(self, *args) -> "void":
        return _halite.UniConnectionVector_insert(self, *args)

    def reserve(self, n: 'std::vector< UniConnection >::size_type') -> "void":
        return _halite.UniConnectionVector_reserve(self, n)

    def capacity(self) -> "std::vector< UniConnection >::size_type":
        return _halite.UniConnectionVector_capacity(self)
    __swig_destroy__ = _halite.delete_UniConnectionVector
    __del__ = lambda self: None
UniConnectionVector_swigregister = _halite.UniConnectionVector_swigregister
UniConnectionVector_swigregister(UniConnectionVector)

class RowVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RowVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RowVector, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _halite.RowVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _halite.RowVector___nonzero__(self)

    def __bool__(self) -> "bool":
        return _halite.RowVector___bool__(self)

    def __len__(self) -> "std::vector< hlt::Site >::size_type":
        return _halite.RowVector___len__(self)

    def __getslice__(self, i: 'std::vector< hlt::Site >::difference_type', j: 'std::vector< hlt::Site >::difference_type') -> "std::vector< hlt::Site,std::allocator< hlt::Site > > *":
        return _halite.RowVector___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _halite.RowVector___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< hlt::Site >::difference_type', j: 'std::vector< hlt::Site >::difference_type') -> "void":
        return _halite.RowVector___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _halite.RowVector___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< hlt::Site >::value_type const &":
        return _halite.RowVector___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _halite.RowVector___setitem__(self, *args)

    def pop(self) -> "std::vector< hlt::Site >::value_type":
        return _halite.RowVector_pop(self)

    def append(self, x: 'Site') -> "void":
        return _halite.RowVector_append(self, x)

    def empty(self) -> "bool":
        return _halite.RowVector_empty(self)

    def size(self) -> "std::vector< hlt::Site >::size_type":
        return _halite.RowVector_size(self)

    def swap(self, v: 'RowVector') -> "void":
        return _halite.RowVector_swap(self, v)

    def begin(self) -> "std::vector< hlt::Site >::iterator":
        return _halite.RowVector_begin(self)

    def end(self) -> "std::vector< hlt::Site >::iterator":
        return _halite.RowVector_end(self)

    def rbegin(self) -> "std::vector< hlt::Site >::reverse_iterator":
        return _halite.RowVector_rbegin(self)

    def rend(self) -> "std::vector< hlt::Site >::reverse_iterator":
        return _halite.RowVector_rend(self)

    def clear(self) -> "void":
        return _halite.RowVector_clear(self)

    def get_allocator(self) -> "std::vector< hlt::Site >::allocator_type":
        return _halite.RowVector_get_allocator(self)

    def pop_back(self) -> "void":
        return _halite.RowVector_pop_back(self)

    def erase(self, *args) -> "std::vector< hlt::Site >::iterator":
        return _halite.RowVector_erase(self, *args)

    def __init__(self, *args):
        this = _halite.new_RowVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x: 'Site') -> "void":
        return _halite.RowVector_push_back(self, x)

    def front(self) -> "std::vector< hlt::Site >::value_type const &":
        return _halite.RowVector_front(self)

    def back(self) -> "std::vector< hlt::Site >::value_type const &":
        return _halite.RowVector_back(self)

    def assign(self, n: 'std::vector< hlt::Site >::size_type', x: 'Site') -> "void":
        return _halite.RowVector_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _halite.RowVector_resize(self, *args)

    def insert(self, *args) -> "void":
        return _halite.RowVector_insert(self, *args)

    def reserve(self, n: 'std::vector< hlt::Site >::size_type') -> "void":
        return _halite.RowVector_reserve(self, n)

    def capacity(self) -> "std::vector< hlt::Site >::size_type":
        return _halite.RowVector_capacity(self)
    __swig_destroy__ = _halite.delete_RowVector
    __del__ = lambda self: None
RowVector_swigregister = _halite.RowVector_swigregister
RowVector_swigregister(RowVector)

class BoardVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BoardVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BoardVector, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _halite.BoardVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _halite.BoardVector___nonzero__(self)

    def __bool__(self) -> "bool":
        return _halite.BoardVector___bool__(self)

    def __len__(self) -> "std::vector< std::vector< hlt::Site > >::size_type":
        return _halite.BoardVector___len__(self)

    def __getslice__(self, i: 'std::vector< std::vector< hlt::Site > >::difference_type', j: 'std::vector< std::vector< hlt::Site > >::difference_type') -> "std::vector< std::vector< hlt::Site,std::allocator< hlt::Site > >,std::allocator< std::vector< hlt::Site,std::allocator< hlt::Site > > > > *":
        return _halite.BoardVector___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _halite.BoardVector___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< std::vector< hlt::Site > >::difference_type', j: 'std::vector< std::vector< hlt::Site > >::difference_type') -> "void":
        return _halite.BoardVector___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _halite.BoardVector___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< std::vector< hlt::Site > >::value_type const &":
        return _halite.BoardVector___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _halite.BoardVector___setitem__(self, *args)

    def pop(self) -> "std::vector< std::vector< hlt::Site > >::value_type":
        return _halite.BoardVector_pop(self)

    def append(self, x: 'RowVector') -> "void":
        return _halite.BoardVector_append(self, x)

    def empty(self) -> "bool":
        return _halite.BoardVector_empty(self)

    def size(self) -> "std::vector< std::vector< hlt::Site > >::size_type":
        return _halite.BoardVector_size(self)

    def swap(self, v: 'BoardVector') -> "void":
        return _halite.BoardVector_swap(self, v)

    def begin(self) -> "std::vector< std::vector< hlt::Site > >::iterator":
        return _halite.BoardVector_begin(self)

    def end(self) -> "std::vector< std::vector< hlt::Site > >::iterator":
        return _halite.BoardVector_end(self)

    def rbegin(self) -> "std::vector< std::vector< hlt::Site > >::reverse_iterator":
        return _halite.BoardVector_rbegin(self)

    def rend(self) -> "std::vector< std::vector< hlt::Site > >::reverse_iterator":
        return _halite.BoardVector_rend(self)

    def clear(self) -> "void":
        return _halite.BoardVector_clear(self)

    def get_allocator(self) -> "std::vector< std::vector< hlt::Site > >::allocator_type":
        return _halite.BoardVector_get_allocator(self)

    def pop_back(self) -> "void":
        return _halite.BoardVector_pop_back(self)

    def erase(self, *args) -> "std::vector< std::vector< hlt::Site > >::iterator":
        return _halite.BoardVector_erase(self, *args)

    def __init__(self, *args):
        this = _halite.new_BoardVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x: 'RowVector') -> "void":
        return _halite.BoardVector_push_back(self, x)

    def front(self) -> "std::vector< std::vector< hlt::Site > >::value_type const &":
        return _halite.BoardVector_front(self)

    def back(self) -> "std::vector< std::vector< hlt::Site > >::value_type const &":
        return _halite.BoardVector_back(self)

    def assign(self, n: 'std::vector< std::vector< hlt::Site > >::size_type', x: 'RowVector') -> "void":
        return _halite.BoardVector_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _halite.BoardVector_resize(self, *args)

    def insert(self, *args) -> "void":
        return _halite.BoardVector_insert(self, *args)

    def reserve(self, n: 'std::vector< std::vector< hlt::Site > >::size_type') -> "void":
        return _halite.BoardVector_reserve(self, n)

    def capacity(self) -> "std::vector< std::vector< hlt::Site > >::size_type":
        return _halite.BoardVector_capacity(self)
    __swig_destroy__ = _halite.delete_BoardVector
    __del__ = lambda self: None
BoardVector_swigregister = _halite.BoardVector_swigregister
BoardVector_swigregister(BoardVector)

class PlayerStatisticsVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PlayerStatisticsVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PlayerStatisticsVector, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _halite.PlayerStatisticsVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _halite.PlayerStatisticsVector___nonzero__(self)

    def __bool__(self) -> "bool":
        return _halite.PlayerStatisticsVector___bool__(self)

    def __len__(self) -> "std::vector< PlayerStatistics >::size_type":
        return _halite.PlayerStatisticsVector___len__(self)

    def __getslice__(self, i: 'std::vector< PlayerStatistics >::difference_type', j: 'std::vector< PlayerStatistics >::difference_type') -> "std::vector< PlayerStatistics,std::allocator< PlayerStatistics > > *":
        return _halite.PlayerStatisticsVector___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _halite.PlayerStatisticsVector___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< PlayerStatistics >::difference_type', j: 'std::vector< PlayerStatistics >::difference_type') -> "void":
        return _halite.PlayerStatisticsVector___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _halite.PlayerStatisticsVector___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< PlayerStatistics >::value_type const &":
        return _halite.PlayerStatisticsVector___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _halite.PlayerStatisticsVector___setitem__(self, *args)

    def pop(self) -> "std::vector< PlayerStatistics >::value_type":
        return _halite.PlayerStatisticsVector_pop(self)

    def append(self, x: 'PlayerStatistics') -> "void":
        return _halite.PlayerStatisticsVector_append(self, x)

    def empty(self) -> "bool":
        return _halite.PlayerStatisticsVector_empty(self)

    def size(self) -> "std::vector< PlayerStatistics >::size_type":
        return _halite.PlayerStatisticsVector_size(self)

    def swap(self, v: 'PlayerStatisticsVector') -> "void":
        return _halite.PlayerStatisticsVector_swap(self, v)

    def begin(self) -> "std::vector< PlayerStatistics >::iterator":
        return _halite.PlayerStatisticsVector_begin(self)

    def end(self) -> "std::vector< PlayerStatistics >::iterator":
        return _halite.PlayerStatisticsVector_end(self)

    def rbegin(self) -> "std::vector< PlayerStatistics >::reverse_iterator":
        return _halite.PlayerStatisticsVector_rbegin(self)

    def rend(self) -> "std::vector< PlayerStatistics >::reverse_iterator":
        return _halite.PlayerStatisticsVector_rend(self)

    def clear(self) -> "void":
        return _halite.PlayerStatisticsVector_clear(self)

    def get_allocator(self) -> "std::vector< PlayerStatistics >::allocator_type":
        return _halite.PlayerStatisticsVector_get_allocator(self)

    def pop_back(self) -> "void":
        return _halite.PlayerStatisticsVector_pop_back(self)

    def erase(self, *args) -> "std::vector< PlayerStatistics >::iterator":
        return _halite.PlayerStatisticsVector_erase(self, *args)

    def __init__(self, *args):
        this = _halite.new_PlayerStatisticsVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x: 'PlayerStatistics') -> "void":
        return _halite.PlayerStatisticsVector_push_back(self, x)

    def front(self) -> "std::vector< PlayerStatistics >::value_type const &":
        return _halite.PlayerStatisticsVector_front(self)

    def back(self) -> "std::vector< PlayerStatistics >::value_type const &":
        return _halite.PlayerStatisticsVector_back(self)

    def assign(self, n: 'std::vector< PlayerStatistics >::size_type', x: 'PlayerStatistics') -> "void":
        return _halite.PlayerStatisticsVector_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _halite.PlayerStatisticsVector_resize(self, *args)

    def insert(self, *args) -> "void":
        return _halite.PlayerStatisticsVector_insert(self, *args)

    def reserve(self, n: 'std::vector< PlayerStatistics >::size_type') -> "void":
        return _halite.PlayerStatisticsVector_reserve(self, n)

    def capacity(self) -> "std::vector< PlayerStatistics >::size_type":
        return _halite.PlayerStatisticsVector_capacity(self)
    __swig_destroy__ = _halite.delete_PlayerStatisticsVector
    __del__ = lambda self: None
PlayerStatisticsVector_swigregister = _halite.PlayerStatisticsVector_swigregister
PlayerStatisticsVector_swigregister(PlayerStatisticsVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _halite.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _halite.StringVector___nonzero__(self)

    def __bool__(self) -> "bool":
        return _halite.StringVector___bool__(self)

    def __len__(self) -> "std::vector< std::string >::size_type":
        return _halite.StringVector___len__(self)

    def __getslice__(self, i: 'std::vector< std::string >::difference_type', j: 'std::vector< std::string >::difference_type') -> "std::vector< std::string,std::allocator< std::string > > *":
        return _halite.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _halite.StringVector___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< std::string >::difference_type', j: 'std::vector< std::string >::difference_type') -> "void":
        return _halite.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _halite.StringVector___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< std::string >::value_type const &":
        return _halite.StringVector___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _halite.StringVector___setitem__(self, *args)

    def pop(self) -> "std::vector< std::string >::value_type":
        return _halite.StringVector_pop(self)

    def append(self, x: 'std::vector< std::string >::value_type const &') -> "void":
        return _halite.StringVector_append(self, x)

    def empty(self) -> "bool":
        return _halite.StringVector_empty(self)

    def size(self) -> "std::vector< std::string >::size_type":
        return _halite.StringVector_size(self)

    def swap(self, v: 'StringVector') -> "void":
        return _halite.StringVector_swap(self, v)

    def begin(self) -> "std::vector< std::string >::iterator":
        return _halite.StringVector_begin(self)

    def end(self) -> "std::vector< std::string >::iterator":
        return _halite.StringVector_end(self)

    def rbegin(self) -> "std::vector< std::string >::reverse_iterator":
        return _halite.StringVector_rbegin(self)

    def rend(self) -> "std::vector< std::string >::reverse_iterator":
        return _halite.StringVector_rend(self)

    def clear(self) -> "void":
        return _halite.StringVector_clear(self)

    def get_allocator(self) -> "std::vector< std::string >::allocator_type":
        return _halite.StringVector_get_allocator(self)

    def pop_back(self) -> "void":
        return _halite.StringVector_pop_back(self)

    def erase(self, *args) -> "std::vector< std::string >::iterator":
        return _halite.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _halite.new_StringVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x: 'std::vector< std::string >::value_type const &') -> "void":
        return _halite.StringVector_push_back(self, x)

    def front(self) -> "std::vector< std::string >::value_type const &":
        return _halite.StringVector_front(self)

    def back(self) -> "std::vector< std::string >::value_type const &":
        return _halite.StringVector_back(self)

    def assign(self, n: 'std::vector< std::string >::size_type', x: 'std::vector< std::string >::value_type const &') -> "void":
        return _halite.StringVector_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _halite.StringVector_resize(self, *args)

    def insert(self, *args) -> "void":
        return _halite.StringVector_insert(self, *args)

    def reserve(self, n: 'std::vector< std::string >::size_type') -> "void":
        return _halite.StringVector_reserve(self, n)

    def capacity(self) -> "std::vector< std::string >::size_type":
        return _halite.StringVector_capacity(self)
    __swig_destroy__ = _halite.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _halite.StringVector_swigregister
StringVector_swigregister(StringVector)

class LocationToMoveMap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LocationToMoveMap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LocationToMoveMap, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _halite.LocationToMoveMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _halite.LocationToMoveMap___nonzero__(self)

    def __bool__(self) -> "bool":
        return _halite.LocationToMoveMap___bool__(self)

    def __len__(self) -> "std::map< hlt::Location,unsigned char >::size_type":
        return _halite.LocationToMoveMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key: 'Location') -> "std::map< hlt::Location,unsigned char >::mapped_type const &":
        return _halite.LocationToMoveMap___getitem__(self, key)

    def __delitem__(self, key: 'Location') -> "void":
        return _halite.LocationToMoveMap___delitem__(self, key)

    def has_key(self, key: 'Location') -> "bool":
        return _halite.LocationToMoveMap_has_key(self, key)

    def keys(self) -> "PyObject *":
        return _halite.LocationToMoveMap_keys(self)

    def values(self) -> "PyObject *":
        return _halite.LocationToMoveMap_values(self)

    def items(self) -> "PyObject *":
        return _halite.LocationToMoveMap_items(self)

    def __contains__(self, key: 'Location') -> "bool":
        return _halite.LocationToMoveMap___contains__(self, key)

    def key_iterator(self) -> "swig::SwigPyIterator *":
        return _halite.LocationToMoveMap_key_iterator(self)

    def value_iterator(self) -> "swig::SwigPyIterator *":
        return _halite.LocationToMoveMap_value_iterator(self)

    def __setitem__(self, *args) -> "void":
        return _halite.LocationToMoveMap___setitem__(self, *args)

    def asdict(self) -> "PyObject *":
        return _halite.LocationToMoveMap_asdict(self)

    def __init__(self, *args):
        this = _halite.new_LocationToMoveMap(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def empty(self) -> "bool":
        return _halite.LocationToMoveMap_empty(self)

    def size(self) -> "std::map< hlt::Location,unsigned char >::size_type":
        return _halite.LocationToMoveMap_size(self)

    def swap(self, v: 'LocationToMoveMap') -> "void":
        return _halite.LocationToMoveMap_swap(self, v)

    def begin(self) -> "std::map< hlt::Location,unsigned char >::iterator":
        return _halite.LocationToMoveMap_begin(self)

    def end(self) -> "std::map< hlt::Location,unsigned char >::iterator":
        return _halite.LocationToMoveMap_end(self)

    def rbegin(self) -> "std::map< hlt::Location,unsigned char >::reverse_iterator":
        return _halite.LocationToMoveMap_rbegin(self)

    def rend(self) -> "std::map< hlt::Location,unsigned char >::reverse_iterator":
        return _halite.LocationToMoveMap_rend(self)

    def clear(self) -> "void":
        return _halite.LocationToMoveMap_clear(self)

    def get_allocator(self) -> "std::map< hlt::Location,unsigned char >::allocator_type":
        return _halite.LocationToMoveMap_get_allocator(self)

    def count(self, x: 'Location') -> "std::map< hlt::Location,unsigned char >::size_type":
        return _halite.LocationToMoveMap_count(self, x)

    def erase(self, *args) -> "void":
        return _halite.LocationToMoveMap_erase(self, *args)

    def find(self, x: 'Location') -> "std::map< hlt::Location,unsigned char >::iterator":
        return _halite.LocationToMoveMap_find(self, x)

    def lower_bound(self, x: 'Location') -> "std::map< hlt::Location,unsigned char >::iterator":
        return _halite.LocationToMoveMap_lower_bound(self, x)

    def upper_bound(self, x: 'Location') -> "std::map< hlt::Location,unsigned char >::iterator":
        return _halite.LocationToMoveMap_upper_bound(self, x)
    __swig_destroy__ = _halite.delete_LocationToMoveMap
    __del__ = lambda self: None
LocationToMoveMap_swigregister = _halite.LocationToMoveMap_swigregister
LocationToMoveMap_swigregister(LocationToMoveMap)

class PlayerMovesVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PlayerMovesVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PlayerMovesVector, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _halite.PlayerMovesVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _halite.PlayerMovesVector___nonzero__(self)

    def __bool__(self) -> "bool":
        return _halite.PlayerMovesVector___bool__(self)

    def __len__(self) -> "std::vector< std::map< hlt::Location,unsigned char > >::size_type":
        return _halite.PlayerMovesVector___len__(self)

    def __getslice__(self, i: 'std::vector< std::map< hlt::Location,unsigned char > >::difference_type', j: 'std::vector< std::map< hlt::Location,unsigned char > >::difference_type') -> "std::vector< std::map< hlt::Location,unsigned char,std::less< hlt::Location >,std::allocator< std::pair< hlt::Location const,unsigned char > > >,std::allocator< std::map< hlt::Location,unsigned char,std::less< hlt::Location >,std::allocator< std::pair< hlt::Location const,unsigned char > > > > > *":
        return _halite.PlayerMovesVector___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _halite.PlayerMovesVector___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< std::map< hlt::Location,unsigned char > >::difference_type', j: 'std::vector< std::map< hlt::Location,unsigned char > >::difference_type') -> "void":
        return _halite.PlayerMovesVector___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _halite.PlayerMovesVector___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< std::map< hlt::Location,unsigned char > >::value_type const &":
        return _halite.PlayerMovesVector___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _halite.PlayerMovesVector___setitem__(self, *args)

    def pop(self) -> "std::vector< std::map< hlt::Location,unsigned char > >::value_type":
        return _halite.PlayerMovesVector_pop(self)

    def append(self, x: 'LocationToMoveMap') -> "void":
        return _halite.PlayerMovesVector_append(self, x)

    def empty(self) -> "bool":
        return _halite.PlayerMovesVector_empty(self)

    def size(self) -> "std::vector< std::map< hlt::Location,unsigned char > >::size_type":
        return _halite.PlayerMovesVector_size(self)

    def swap(self, v: 'PlayerMovesVector') -> "void":
        return _halite.PlayerMovesVector_swap(self, v)

    def begin(self) -> "std::vector< std::map< hlt::Location,unsigned char > >::iterator":
        return _halite.PlayerMovesVector_begin(self)

    def end(self) -> "std::vector< std::map< hlt::Location,unsigned char > >::iterator":
        return _halite.PlayerMovesVector_end(self)

    def rbegin(self) -> "std::vector< std::map< hlt::Location,unsigned char > >::reverse_iterator":
        return _halite.PlayerMovesVector_rbegin(self)

    def rend(self) -> "std::vector< std::map< hlt::Location,unsigned char > >::reverse_iterator":
        return _halite.PlayerMovesVector_rend(self)

    def clear(self) -> "void":
        return _halite.PlayerMovesVector_clear(self)

    def get_allocator(self) -> "std::vector< std::map< hlt::Location,unsigned char > >::allocator_type":
        return _halite.PlayerMovesVector_get_allocator(self)

    def pop_back(self) -> "void":
        return _halite.PlayerMovesVector_pop_back(self)

    def erase(self, *args) -> "std::vector< std::map< hlt::Location,unsigned char > >::iterator":
        return _halite.PlayerMovesVector_erase(self, *args)

    def __init__(self, *args):
        this = _halite.new_PlayerMovesVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x: 'LocationToMoveMap') -> "void":
        return _halite.PlayerMovesVector_push_back(self, x)

    def front(self) -> "std::vector< std::map< hlt::Location,unsigned char > >::value_type const &":
        return _halite.PlayerMovesVector_front(self)

    def back(self) -> "std::vector< std::map< hlt::Location,unsigned char > >::value_type const &":
        return _halite.PlayerMovesVector_back(self)

    def assign(self, n: 'std::vector< std::map< hlt::Location,unsigned char > >::size_type', x: 'LocationToMoveMap') -> "void":
        return _halite.PlayerMovesVector_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _halite.PlayerMovesVector_resize(self, *args)

    def insert(self, *args) -> "void":
        return _halite.PlayerMovesVector_insert(self, *args)

    def reserve(self, n: 'std::vector< std::map< hlt::Location,unsigned char > >::size_type') -> "void":
        return _halite.PlayerMovesVector_reserve(self, n)

    def capacity(self) -> "std::vector< std::map< hlt::Location,unsigned char > >::size_type":
        return _halite.PlayerMovesVector_capacity(self)
    __swig_destroy__ = _halite.delete_PlayerMovesVector
    __del__ = lambda self: None
PlayerMovesVector_swigregister = _halite.PlayerMovesVector_swigregister
PlayerMovesVector_swigregister(PlayerMovesVector)

class GameCallback(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GameCallback, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GameCallback, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _halite.delete_GameCallback
    __del__ = lambda self: None

    def endGame(self, turn: 'int', board: 'Map') -> "bool":
        return _halite.GameCallback_endGame(self, turn, board)

    def playerInitTimeout(self, playerTag: 'unsigned char') -> "void":
        return _halite.GameCallback_playerInitTimeout(self, playerTag)

    def playerFrameTimeout(self, playerTag: 'unsigned char') -> "void":
        return _halite.GameCallback_playerFrameTimeout(self, playerTag)

    def __init__(self):
        if self.__class__ == GameCallback:
            _self = None
        else:
            _self = self
        this = _halite.new_GameCallback(_self, )
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    def __disown__(self):
        self.this.disown()
        _halite.disown_GameCallback(self)
        return weakref_proxy(self)
GameCallback_swigregister = _halite.GameCallback_swigregister
GameCallback_swigregister(GameCallback)

STILL = _halite.STILL
NORTH = _halite.NORTH
EAST = _halite.EAST
SOUTH = _halite.SOUTH
WEST = _halite.WEST
class Color(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Color, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Color, name)
    __repr__ = _swig_repr
    __swig_setmethods__["r"] = _halite.Color_r_set
    __swig_getmethods__["r"] = _halite.Color_r_get
    if _newclass:
        r = _swig_property(_halite.Color_r_get, _halite.Color_r_set)
    __swig_setmethods__["g"] = _halite.Color_g_set
    __swig_getmethods__["g"] = _halite.Color_g_get
    if _newclass:
        g = _swig_property(_halite.Color_g_get, _halite.Color_g_set)
    __swig_setmethods__["b"] = _halite.Color_b_set
    __swig_getmethods__["b"] = _halite.Color_b_get
    if _newclass:
        b = _swig_property(_halite.Color_b_get, _halite.Color_b_set)

    def __init__(self):
        this = _halite.new_Color()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _halite.delete_Color
    __del__ = lambda self: None
Color_swigregister = _halite.Color_swigregister
Color_swigregister(Color)
cvar = _halite.cvar

class PlayerStatistics(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PlayerStatistics, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PlayerStatistics, name)
    __repr__ = _swig_repr
    __swig_setmethods__["tag"] = _halite.PlayerStatistics_tag_set
    __swig_getmethods__["tag"] = _halite.PlayerStatistics_tag_get
    if _newclass:
        tag = _swig_property(_halite.PlayerStatistics_tag_get, _halite.PlayerStatistics_tag_set)
    __swig_setmethods__["rank"] = _halite.PlayerStatistics_rank_set
    __swig_getmethods__["rank"] = _halite.PlayerStatistics_rank_get
    if _newclass:
        rank = _swig_property(_halite.PlayerStatistics_rank_get, _halite.PlayerStatistics_rank_set)
    __swig_setmethods__["average_territory_count"] = _halite.PlayerStatistics_average_territory_count_set
    __swig_getmethods__["average_territory_count"] = _halite.PlayerStatistics_average_territory_count_get
    if _newclass:
        average_territory_count = _swig_property(_halite.PlayerStatistics_average_territory_count_get, _halite.PlayerStatistics_average_territory_count_set)
    __swig_setmethods__["average_strength_count"] = _halite.PlayerStatistics_average_strength_count_set
    __swig_getmethods__["average_strength_count"] = _halite.PlayerStatistics_average_strength_count_get
    if _newclass:
        average_strength_count = _swig_property(_halite.PlayerStatistics_average_strength_count_get, _halite.PlayerStatistics_average_strength_count_set)
    __swig_setmethods__["average_production_count"] = _halite.PlayerStatistics_average_production_count_set
    __swig_getmethods__["average_production_count"] = _halite.PlayerStatistics_average_production_count_get
    if _newclass:
        average_production_count = _swig_property(_halite.PlayerStatistics_average_production_count_get, _halite.PlayerStatistics_average_production_count_set)
    __swig_setmethods__["still_percentage"] = _halite.PlayerStatistics_still_percentage_set
    __swig_getmethods__["still_percentage"] = _halite.PlayerStatistics_still_percentage_get
    if _newclass:
        still_percentage = _swig_property(_halite.PlayerStatistics_still_percentage_get, _halite.PlayerStatistics_still_percentage_set)
    __swig_setmethods__["init_response_time"] = _halite.PlayerStatistics_init_response_time_set
    __swig_getmethods__["init_response_time"] = _halite.PlayerStatistics_init_response_time_get
    if _newclass:
        init_response_time = _swig_property(_halite.PlayerStatistics_init_response_time_get, _halite.PlayerStatistics_init_response_time_set)
    __swig_setmethods__["average_frame_response_time"] = _halite.PlayerStatistics_average_frame_response_time_set
    __swig_getmethods__["average_frame_response_time"] = _halite.PlayerStatistics_average_frame_response_time_get
    if _newclass:
        average_frame_response_time = _swig_property(_halite.PlayerStatistics_average_frame_response_time_get, _halite.PlayerStatistics_average_frame_response_time_set)

    def __init__(self):
        this = _halite.new_PlayerStatistics()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _halite.delete_PlayerStatistics
    __del__ = lambda self: None
PlayerStatistics_swigregister = _halite.PlayerStatistics_swigregister
PlayerStatistics_swigregister(PlayerStatistics)

class GameStatistics(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GameStatistics, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GameStatistics, name)
    __repr__ = _swig_repr
    __swig_setmethods__["player_statistics"] = _halite.GameStatistics_player_statistics_set
    __swig_getmethods__["player_statistics"] = _halite.GameStatistics_player_statistics_get
    if _newclass:
        player_statistics = _swig_property(_halite.GameStatistics_player_statistics_get, _halite.GameStatistics_player_statistics_set)
    __swig_setmethods__["output_filename"] = _halite.GameStatistics_output_filename_set
    __swig_getmethods__["output_filename"] = _halite.GameStatistics_output_filename_get
    if _newclass:
        output_filename = _swig_property(_halite.GameStatistics_output_filename_get, _halite.GameStatistics_output_filename_set)
    __swig_setmethods__["timeout_tags"] = _halite.GameStatistics_timeout_tags_set
    __swig_getmethods__["timeout_tags"] = _halite.GameStatistics_timeout_tags_get
    if _newclass:
        timeout_tags = _swig_property(_halite.GameStatistics_timeout_tags_get, _halite.GameStatistics_timeout_tags_set)
    __swig_setmethods__["timeout_log_filenames"] = _halite.GameStatistics_timeout_log_filenames_set
    __swig_getmethods__["timeout_log_filenames"] = _halite.GameStatistics_timeout_log_filenames_get
    if _newclass:
        timeout_log_filenames = _swig_property(_halite.GameStatistics_timeout_log_filenames_get, _halite.GameStatistics_timeout_log_filenames_set)

    def __init__(self):
        this = _halite.new_GameStatistics()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _halite.delete_GameStatistics
    __del__ = lambda self: None
GameStatistics_swigregister = _halite.GameStatistics_swigregister
GameStatistics_swigregister(GameStatistics)

class Location(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Location, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Location, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _halite.Location_x_set
    __swig_getmethods__["x"] = _halite.Location_x_get
    if _newclass:
        x = _swig_property(_halite.Location_x_get, _halite.Location_x_set)
    __swig_setmethods__["y"] = _halite.Location_y_set
    __swig_getmethods__["y"] = _halite.Location_y_get
    if _newclass:
        y = _swig_property(_halite.Location_y_get, _halite.Location_y_set)

    def __init__(self):
        this = _halite.new_Location()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _halite.delete_Location
    __del__ = lambda self: None
Location_swigregister = _halite.Location_swigregister
Location_swigregister(Location)


def __lt__(l1: 'Location', l2: 'Location') -> "bool":
    return _halite.__lt__(l1, l2)
__lt__ = _halite.__lt__

def __eq__(l1: 'Location', l2: 'Location') -> "bool":
    return _halite.__eq__(l1, l2)
__eq__ = _halite.__eq__
class Site(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Site, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Site, name)
    __repr__ = _swig_repr
    __swig_setmethods__["owner"] = _halite.Site_owner_set
    __swig_getmethods__["owner"] = _halite.Site_owner_get
    if _newclass:
        owner = _swig_property(_halite.Site_owner_get, _halite.Site_owner_set)
    __swig_setmethods__["strength"] = _halite.Site_strength_set
    __swig_getmethods__["strength"] = _halite.Site_strength_get
    if _newclass:
        strength = _swig_property(_halite.Site_strength_get, _halite.Site_strength_set)
    __swig_setmethods__["production"] = _halite.Site_production_set
    __swig_getmethods__["production"] = _halite.Site_production_get
    if _newclass:
        production = _swig_property(_halite.Site_production_get, _halite.Site_production_set)

    def __init__(self):
        this = _halite.new_Site()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _halite.delete_Site
    __del__ = lambda self: None
Site_swigregister = _halite.Site_swigregister
Site_swigregister(Site)

class Map(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Map, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Map, name)
    __repr__ = _swig_repr
    __swig_setmethods__["contents"] = _halite.Map_contents_set
    __swig_getmethods__["contents"] = _halite.Map_contents_get
    if _newclass:
        contents = _swig_property(_halite.Map_contents_get, _halite.Map_contents_set)
    __swig_setmethods__["width"] = _halite.Map_width_set
    __swig_getmethods__["width"] = _halite.Map_width_get
    if _newclass:
        width = _swig_property(_halite.Map_width_get, _halite.Map_width_set)
    __swig_setmethods__["height"] = _halite.Map_height_set
    __swig_getmethods__["height"] = _halite.Map_height_get
    if _newclass:
        height = _swig_property(_halite.Map_height_get, _halite.Map_height_set)

    def __init__(self, *args):
        this = _halite.new_Map(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def inBounds(self, l: 'Location') -> "bool":
        return _halite.Map_inBounds(self, l)

    def getDistance(self, l1: 'Location', l2: 'Location') -> "float":
        return _halite.Map_getDistance(self, l1, l2)

    def getAngle(self, l1: 'Location', l2: 'Location') -> "float":
        return _halite.Map_getAngle(self, l1, l2)

    def getLocation(self, l: 'Location', direction: 'unsigned char') -> "hlt::Location":
        return _halite.Map_getLocation(self, l, direction)

    def getSite(self, l: 'Location', direction: 'unsigned char'=0) -> "hlt::Site &":
        return _halite.Map_getSite(self, l, direction)
    __swig_destroy__ = _halite.delete_Map
    __del__ = lambda self: None
Map_swigregister = _halite.Map_swigregister
Map_swigregister(Map)


def ppmToMap(filename: 'std::string', numplayers: 'int') -> "hlt::Map":
    return _halite.ppmToMap(filename, numplayers)
ppmToMap = _halite.ppmToMap
class UniConnection(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UniConnection, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UniConnection, name)
    __repr__ = _swig_repr
    __swig_setmethods__["read"] = _halite.UniConnection_read_set
    __swig_getmethods__["read"] = _halite.UniConnection_read_get
    if _newclass:
        read = _swig_property(_halite.UniConnection_read_get, _halite.UniConnection_read_set)
    __swig_setmethods__["write"] = _halite.UniConnection_write_set
    __swig_getmethods__["write"] = _halite.UniConnection_write_get
    if _newclass:
        write = _swig_property(_halite.UniConnection_write_get, _halite.UniConnection_write_set)

    def __init__(self):
        this = _halite.new_UniConnection()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _halite.delete_UniConnection
    __del__ = lambda self: None
UniConnection_swigregister = _halite.UniConnection_swigregister
UniConnection_swigregister(UniConnection)

class Networking(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Networking, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Networking, name)
    __repr__ = _swig_repr

    def startAndConnectBot(self, command: 'std::string') -> "void":
        return _halite.Networking_startAndConnectBot(self, command)

    def handleInitNetworking(self, playerTag: 'unsigned char', m: 'Map', ignoreTimeout: 'bool', playerName: 'std::string *') -> "int":
        return _halite.Networking_handleInitNetworking(self, playerTag, m, ignoreTimeout, playerName)

    def handleFrameNetworking(self, playerTag: 'unsigned char', turnNumber: 'unsigned short const &', m: 'Map', ignoreTimeout: 'bool', moves: 'LocationToMoveMap') -> "int":
        return _halite.Networking_handleFrameNetworking(self, playerTag, turnNumber, m, ignoreTimeout, moves)

    def killPlayer(self, playerTag: 'unsigned char') -> "void":
        return _halite.Networking_killPlayer(self, playerTag)

    def isProcessDead(self, playerTag: 'unsigned char') -> "bool":
        return _halite.Networking_isProcessDead(self, playerTag)

    def numberOfPlayers(self) -> "int":
        return _halite.Networking_numberOfPlayers(self)
    __swig_setmethods__["player_logs"] = _halite.Networking_player_logs_set
    __swig_getmethods__["player_logs"] = _halite.Networking_player_logs_get
    if _newclass:
        player_logs = _swig_property(_halite.Networking_player_logs_get, _halite.Networking_player_logs_set)
    if _newclass:
        serializeMap = staticmethod(_halite.Networking_serializeMap)
    else:
        serializeMap = _halite.Networking_serializeMap

    def addLocalBot(self, connection: 'UniConnection') -> "void":
        return _halite.Networking_addLocalBot(self, connection)

    def stopManagingProcesses(self) -> "void":
        return _halite.Networking_stopManagingProcesses(self)

    def __init__(self):
        this = _halite.new_Networking()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _halite.delete_Networking
    __del__ = lambda self: None
Networking_swigregister = _halite.Networking_swigregister
Networking_swigregister(Networking)

def Networking_serializeMap(map: 'Map') -> "std::string":
    return _halite.Networking_serializeMap(map)
Networking_serializeMap = _halite.Networking_serializeMap


def setQuietOutput(quiet_output: 'bool') -> "void":
    return _halite.setQuietOutput(quiet_output)
setQuietOutput = _halite.setQuietOutput

def randomMap(width: 'short', height: 'short', numberOfPlayers: 'unsigned char', seed: 'unsigned int') -> "hlt::Map":
    return _halite.randomMap(width, height, numberOfPlayers, seed)
randomMap = _halite.randomMap

def randomMapString(width: 'short', height: 'short', numberOfPlayers: 'unsigned char', seed: 'unsigned int') -> "std::string":
    return _halite.randomMapString(width, height, numberOfPlayers, seed)
randomMapString = _halite.randomMapString

def randomSeed() -> "unsigned int":
    return _halite.randomSeed()
randomSeed = _halite.randomSeed

def blankMap(width: 'short', height: 'short') -> "hlt::Map":
    return _halite.blankMap(width, height)
blankMap = _halite.blankMap
class GameRun(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GameRun, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GameRun, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _halite.new_GameRun()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _halite.delete_GameRun
    __del__ = lambda self: None
    __swig_setmethods__["stats"] = _halite.GameRun_stats_set
    __swig_getmethods__["stats"] = _halite.GameRun_stats_get
    if _newclass:
        stats = _swig_property(_halite.GameRun_stats_get, _halite.GameRun_stats_set)
    __swig_setmethods__["map"] = _halite.GameRun_map_set
    __swig_getmethods__["map"] = _halite.GameRun_map_get
    if _newclass:
        map = _swig_property(_halite.GameRun_map_get, _halite.GameRun_map_set)
GameRun_swigregister = _halite.GameRun_swigregister
GameRun_swigregister(GameRun)


def runGame(id: 'unsigned int', width: 'short', height: 'short', seed: 'unsigned int', ignore_timeout: 'bool', connections: 'UniConnectionVector', callback: 'GameCallback') -> "GameRun":
    return _halite.runGame(id, width, height, seed, ignore_timeout, connections, callback)
runGame = _halite.runGame

def updateMap(game_map: 'Map', player_moves: 'PlayerMovesVector') -> "void":
    return _halite.updateMap(game_map, player_moves)
updateMap = _halite.updateMap
# This file is compatible with both classic and new-style classes.


