/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: halite.i

#define SWIGMODULE halite
#define SWIG_DIRECTORS

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "../halite.hpp"
#include "../networking/Networking.cpp"
#include "../core/Halite.cpp"


#include <string>


#include <vector>
#include <stdexcept>

SWIGINTERN std::vector< UniConnection >::const_reference std_vector_Sl_UniConnection_Sg__get(std::vector< UniConnection > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_UniConnection_Sg__set(std::vector< UniConnection > *self,int i,std::vector< UniConnection >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }

// C++ director class methods.
#include "halite_wrap.h"


#include <map>

namespace {
  struct GCItem {
    virtual ~GCItem() {}
  };

  struct GCItem_var {
    GCItem_var(GCItem *item = 0) : _item(item) {
    }

    GCItem_var& operator=(GCItem *item) {
      GCItem *tmp = _item;
      _item = item;
      delete tmp;
      return *this;
    }

    ~GCItem_var() {
      delete _item;
    }

    GCItem* operator->() {
      return _item;
    }

    private:
      GCItem *_item;
  };

  template <typename Type>
  struct GCItem_T : GCItem {
    GCItem_T(Type *ptr) : _ptr(ptr) {
    }

    virtual ~GCItem_T() {
      delete _ptr;
    }

  private:
    Type *_ptr;
  };
}

class Swig_memory {
public:
  template <typename Type>
  void swig_acquire_pointer(Type* vptr) {
    if (vptr) {
      swig_owner[vptr] = new GCItem_T<Type>(vptr);
    }
  }
private:
  typedef std::map<void *, GCItem_var> swig_ownership_map;
  swig_ownership_map swig_owner;
};

template <typename Type>
static void swig_acquire_pointer(Swig_memory** pmem, Type* ptr) {
  if (!pmem) {
    *pmem = new Swig_memory;
  }
  (*pmem)->swig_acquire_pointer(ptr);
}

SwigDirector_GameEndCallback::SwigDirector_GameEndCallback(int swig_p)
    : GameEndCallback(),
      go_val(swig_p), swig_mem(0)
{ }

extern "C" void Swiggo_DeleteDirector_GameEndCallback_halite_2007760261f40110(intgo);
SwigDirector_GameEndCallback::~SwigDirector_GameEndCallback()
{
  Swiggo_DeleteDirector_GameEndCallback_halite_2007760261f40110(go_val);
  delete swig_mem;
}

extern "C" bool Swig_DirectorGameEndCallback_callback_run_halite_2007760261f40110(int, intgo arg2, _gostring_ arg3);
bool SwigDirector_GameEndCallback::run(int turn, std::string board) {
  bool c_result;
  bool result;
  intgo swig_arg2;
  _gostring_ swig_arg3;
  
  swig_arg2 = (int)turn; 
  swig_arg3 = Swig_AllocateString((&board)->data(), (&board)->length()); 
  result = Swig_DirectorGameEndCallback_callback_run_halite_2007760261f40110(go_val, swig_arg2, swig_arg3);
  c_result = (bool)result; 
  return c_result;
}

SwigDirector_TimeoutCallback::SwigDirector_TimeoutCallback(int swig_p)
    : TimeoutCallback(),
      go_val(swig_p), swig_mem(0)
{ }

extern "C" void Swiggo_DeleteDirector_TimeoutCallback_halite_2007760261f40110(intgo);
SwigDirector_TimeoutCallback::~SwigDirector_TimeoutCallback()
{
  Swiggo_DeleteDirector_TimeoutCallback_halite_2007760261f40110(go_val);
  delete swig_mem;
}

extern "C" void Swig_DirectorTimeoutCallback_callback_run_halite_2007760261f40110(int, intgo arg2, _gostring_ arg3);
void SwigDirector_TimeoutCallback::run(int playerTag, std::string playerName) {
  intgo swig_arg2;
  _gostring_ swig_arg3;
  
  swig_arg2 = (int)playerTag; 
  swig_arg3 = Swig_AllocateString((&playerName)->data(), (&playerName)->length()); 
  Swig_DirectorTimeoutCallback_callback_run_halite_2007760261f40110(go_val, swig_arg2, swig_arg3);
}

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_halite_2007760261f40110(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_halite_2007760261f40110(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_quiet_output_set_halite_2007760261f40110(bool _swig_go_0) {
  bool arg1 ;
  
  arg1 = (bool)_swig_go_0; 
  
  quiet_output = arg1;
  
}


bool _wrap_quiet_output_get_halite_2007760261f40110() {
  bool result;
  bool _swig_go_result;
  
  
  result = (bool)quiet_output;
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_randomMap_halite_2007760261f40110(short _swig_go_0, short _swig_go_1, char _swig_go_2, intgo _swig_go_3) {
  short arg1 ;
  short arg2 ;
  unsigned char arg3 ;
  unsigned int arg4 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = (short)_swig_go_0; 
  arg2 = (short)_swig_go_1; 
  arg3 = (unsigned char)_swig_go_2; 
  arg4 = (unsigned int)_swig_go_3; 
  
  result = halite::randomMap(arg1,arg2,arg3,arg4);
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


GameStatistics *_wrap_rawRunGame_halite_2007760261f40110(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, intgo _swig_go_3, bool _swig_go_4, std::vector< UniConnection > *_swig_go_5, GameEndCallback *_swig_go_6) {
  unsigned int arg1 ;
  short arg2 ;
  short arg3 ;
  unsigned int arg4 ;
  bool arg5 ;
  std::vector< UniConnection > arg6 ;
  GameEndCallback *arg7 = (GameEndCallback *) 0 ;
  std::vector< UniConnection > *argp6 ;
  GameStatistics result;
  GameStatistics *_swig_go_result;
  
  arg1 = (unsigned int)_swig_go_0; 
  arg2 = (short)_swig_go_1; 
  arg3 = (short)_swig_go_2; 
  arg4 = (unsigned int)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  
  argp6 = (std::vector< UniConnection > *)_swig_go_5;
  if (argp6 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< UniConnection >");
  }
  arg6 = (std::vector< UniConnection >)*argp6;
  
  arg7 = *(GameEndCallback **)&_swig_go_6; 
  
  result = halite::rawRunGame(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  *(GameStatistics **)&_swig_go_result = new GameStatistics(result); 
  return _swig_go_result;
}


GameEndCallback *_wrap__swig_NewDirectorGameEndCallbackGameEndCallback_halite_2007760261f40110(intgo _swig_go_0) {
  int arg1 ;
  GameEndCallback *result = 0 ;
  GameEndCallback *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = new SwigDirector_GameEndCallback(arg1);
  *(GameEndCallback **)&_swig_go_result = (GameEndCallback *)result; 
  return _swig_go_result;
}


void _wrap_DeleteDirectorGameEndCallback_halite_2007760261f40110(GameEndCallback *_swig_go_0) {
  GameEndCallback *arg1 = (GameEndCallback *) 0 ;
  
  arg1 = *(GameEndCallback **)&_swig_go_0; 
  
  delete arg1;
  
}


bool _wrap__swig_DirectorGameEndCallback_upcall_Run_halite_2007760261f40110(SwigDirector_GameEndCallback *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  SwigDirector_GameEndCallback *arg1 = (SwigDirector_GameEndCallback *) 0 ;
  int arg2 ;
  std::string arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(SwigDirector_GameEndCallback **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  (&arg3)->assign(_swig_go_2.p, _swig_go_2.n); 
  
  result = (bool)arg1->_swig_upcall_run(arg2, arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_delete_GameEndCallback_halite_2007760261f40110(GameEndCallback *_swig_go_0) {
  GameEndCallback *arg1 = (GameEndCallback *) 0 ;
  
  arg1 = *(GameEndCallback **)&_swig_go_0; 
  
  delete arg1;
  
}


bool _wrap_GameEndCallback_run_halite_2007760261f40110(GameEndCallback *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  GameEndCallback *arg1 = (GameEndCallback *) 0 ;
  int arg2 ;
  std::string arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GameEndCallback **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  (&arg3)->assign(_swig_go_2.p, _swig_go_2.n); 
  
  result = (bool)(arg1)->run(arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


GameEndCallback *_wrap_new_GameEndCallback_halite_2007760261f40110() {
  GameEndCallback *result = 0 ;
  GameEndCallback *_swig_go_result;
  
  
  result = (GameEndCallback *)new GameEndCallback();
  *(GameEndCallback **)&_swig_go_result = (GameEndCallback *)result; 
  return _swig_go_result;
}


TimeoutCallback *_wrap__swig_NewDirectorTimeoutCallbackTimeoutCallback_halite_2007760261f40110(intgo _swig_go_0) {
  int arg1 ;
  TimeoutCallback *result = 0 ;
  TimeoutCallback *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = new SwigDirector_TimeoutCallback(arg1);
  *(TimeoutCallback **)&_swig_go_result = (TimeoutCallback *)result; 
  return _swig_go_result;
}


void _wrap_DeleteDirectorTimeoutCallback_halite_2007760261f40110(TimeoutCallback *_swig_go_0) {
  TimeoutCallback *arg1 = (TimeoutCallback *) 0 ;
  
  arg1 = *(TimeoutCallback **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap__swig_DirectorTimeoutCallback_upcall_Run_halite_2007760261f40110(SwigDirector_TimeoutCallback *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  SwigDirector_TimeoutCallback *arg1 = (SwigDirector_TimeoutCallback *) 0 ;
  int arg2 ;
  std::string arg3 ;
  
  arg1 = *(SwigDirector_TimeoutCallback **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  (&arg3)->assign(_swig_go_2.p, _swig_go_2.n); 
  
  arg1->_swig_upcall_run(arg2, arg3);
  
}


void _wrap_delete_TimeoutCallback_halite_2007760261f40110(TimeoutCallback *_swig_go_0) {
  TimeoutCallback *arg1 = (TimeoutCallback *) 0 ;
  
  arg1 = *(TimeoutCallback **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_TimeoutCallback_run_halite_2007760261f40110(TimeoutCallback *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  TimeoutCallback *arg1 = (TimeoutCallback *) 0 ;
  int arg2 ;
  std::string arg3 ;
  
  arg1 = *(TimeoutCallback **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  (&arg3)->assign(_swig_go_2.p, _swig_go_2.n); 
  
  (arg1)->run(arg2,arg3);
  
}


TimeoutCallback *_wrap_new_TimeoutCallback_halite_2007760261f40110() {
  TimeoutCallback *result = 0 ;
  TimeoutCallback *_swig_go_result;
  
  
  result = (TimeoutCallback *)new TimeoutCallback();
  *(TimeoutCallback **)&_swig_go_result = (TimeoutCallback *)result; 
  return _swig_go_result;
}


std::vector< UniConnection > *_wrap_new_UniConnectionVector__SWIG_0_halite_2007760261f40110() {
  std::vector< UniConnection > *result = 0 ;
  std::vector< UniConnection > *_swig_go_result;
  
  
  result = (std::vector< UniConnection > *)new std::vector< UniConnection >();
  *(std::vector< UniConnection > **)&_swig_go_result = (std::vector< UniConnection > *)result; 
  return _swig_go_result;
}


std::vector< UniConnection > *_wrap_new_UniConnectionVector__SWIG_1_halite_2007760261f40110(long long _swig_go_0) {
  std::vector< UniConnection >::size_type arg1 ;
  std::vector< UniConnection > *result = 0 ;
  std::vector< UniConnection > *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  
  result = (std::vector< UniConnection > *)new std::vector< UniConnection >(arg1);
  *(std::vector< UniConnection > **)&_swig_go_result = (std::vector< UniConnection > *)result; 
  return _swig_go_result;
}


long long _wrap_UniConnectionVector_size_halite_2007760261f40110(std::vector< UniConnection > *_swig_go_0) {
  std::vector< UniConnection > *arg1 = (std::vector< UniConnection > *) 0 ;
  std::vector< UniConnection >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< UniConnection > **)&_swig_go_0; 
  
  result = ((std::vector< UniConnection > const *)arg1)->size();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_UniConnectionVector_capacity_halite_2007760261f40110(std::vector< UniConnection > *_swig_go_0) {
  std::vector< UniConnection > *arg1 = (std::vector< UniConnection > *) 0 ;
  std::vector< UniConnection >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< UniConnection > **)&_swig_go_0; 
  
  result = ((std::vector< UniConnection > const *)arg1)->capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_UniConnectionVector_reserve_halite_2007760261f40110(std::vector< UniConnection > *_swig_go_0, long long _swig_go_1) {
  std::vector< UniConnection > *arg1 = (std::vector< UniConnection > *) 0 ;
  std::vector< UniConnection >::size_type arg2 ;
  
  arg1 = *(std::vector< UniConnection > **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  (arg1)->reserve(arg2);
  
}


bool _wrap_UniConnectionVector_isEmpty_halite_2007760261f40110(std::vector< UniConnection > *_swig_go_0) {
  std::vector< UniConnection > *arg1 = (std::vector< UniConnection > *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(std::vector< UniConnection > **)&_swig_go_0; 
  
  result = (bool)((std::vector< UniConnection > const *)arg1)->empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_UniConnectionVector_clear_halite_2007760261f40110(std::vector< UniConnection > *_swig_go_0) {
  std::vector< UniConnection > *arg1 = (std::vector< UniConnection > *) 0 ;
  
  arg1 = *(std::vector< UniConnection > **)&_swig_go_0; 
  
  (arg1)->clear();
  
}


void _wrap_UniConnectionVector_add_halite_2007760261f40110(std::vector< UniConnection > *_swig_go_0, UniConnection *_swig_go_1) {
  std::vector< UniConnection > *arg1 = (std::vector< UniConnection > *) 0 ;
  std::vector< UniConnection >::value_type *arg2 = 0 ;
  
  arg1 = *(std::vector< UniConnection > **)&_swig_go_0; 
  arg2 = *(std::vector< UniConnection >::value_type **)&_swig_go_1; 
  
  (arg1)->push_back((std::vector< UniConnection >::value_type const &)*arg2);
  
}


UniConnection *_wrap_UniConnectionVector_get_halite_2007760261f40110(std::vector< UniConnection > *_swig_go_0, intgo _swig_go_1) {
  std::vector< UniConnection > *arg1 = (std::vector< UniConnection > *) 0 ;
  int arg2 ;
  std::vector< UniConnection >::value_type *result = 0 ;
  UniConnection *_swig_go_result;
  
  arg1 = *(std::vector< UniConnection > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  try {
    result = (std::vector< UniConnection >::value_type *) &std_vector_Sl_UniConnection_Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  
  *(std::vector< UniConnection >::value_type **)&_swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_UniConnectionVector_set_halite_2007760261f40110(std::vector< UniConnection > *_swig_go_0, intgo _swig_go_1, UniConnection *_swig_go_2) {
  std::vector< UniConnection > *arg1 = (std::vector< UniConnection > *) 0 ;
  int arg2 ;
  std::vector< UniConnection >::value_type *arg3 = 0 ;
  
  arg1 = *(std::vector< UniConnection > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(std::vector< UniConnection >::value_type **)&_swig_go_2; 
  
  try {
    std_vector_Sl_UniConnection_Sg__set(arg1,arg2,(UniConnection const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  
  
}


void _wrap_delete_UniConnectionVector_halite_2007760261f40110(std::vector< UniConnection > *_swig_go_0) {
  std::vector< UniConnection > *arg1 = (std::vector< UniConnection > *) 0 ;
  
  arg1 = *(std::vector< UniConnection > **)&_swig_go_0; 
  
  delete arg1;
  
}


#ifdef __cplusplus
}
#endif

